### ISSUE TITLE
Add a way for bot to optionally assign roles to Discord Users based off of their ranking on the server

### ISSUE THREAD

**Issue by Tdortiz** [Tdortiz/PUBG-Buddy#35]
**Describe the solution you'd like**
I want to be able to run a leaderboard ranking command (similar to top) that will set `Discord Server Roles` on my server for each person. 

This command should be ran only by admins of the server.

Role Ranges:

![image](https://user-images.githubusercontent.com/10877317/46778776-35f9b580-cce3-11e8-8eb8-b83a4750ad13.png)

# Permission
* Will need `MANAGE_ROLES` permissions to manage roles on a server.

# Potential Issues
* Currently anyone can run `addUser` to add anyone to the server tracking list. If we add role capability we would need to do something like the following `addUser Thomas-O @Thomas`

## Potential Resources
* https://www.youtube.com/watch?v=hDz7iTtalAY
* https://anidiotsguide_old.gitbooks.io/discord-js-bot-guide/content/information/understanding-roles.html

# Notes
* Get guild member by id - `const member = message.guild.member(userID);`
* Current `addUser` only adds a pubg-specified name to a server registery but **DOES NOT** record/give the option to record the Discord ID of a Discord User to map to a PUBG Player. 
  * Without this kind of mapping functionality (maybe an extra param) we cannot assign roles
* `msg.guild.members.get(msg.author.id).displayName`

**Comment by Marrett13** [comment]
Hey TDortiz, great work on your Discord Bot!

I was wandering have you got anywhere with this yet?

I am looking to try and code it myself, but if it has already been done, why reinvent the wheel :)

**Comment by Tdortiz** [comment]
@Marrett13 This change is address in #50 and is now live.
